package Damas.entity;
// Generated 04/03/2020 19:27:52 by Hibernate Tools 4.3.1



/**
 * Moviment generated by hbm2java
 */
public class Moviment  implements java.io.Serializable {


     public MovimentId id;
     private Partida partida;
     private String taula;

    public Moviment() {
    }

    public Moviment(MovimentId id, Partida partida, String taula) {
       this.id = id;
       this.partida = partida;
       this.taula = taula;
    }
   
    public MovimentId getId() {
        return this.id;
    }
    
    public void setId(MovimentId id) {
        this.id = id;
    }
    public Partida getPartida() {
        return this.partida;
    }
    
    public void setPartida(Partida partida) {
        this.partida = partida;
    }
    public String getTaula() {
        return this.taula;
    }
    
    public void setTaula(String taula) {
        this.taula = taula;
    }




}


