package Damas.entity;
// Generated 04/03/2020 19:27:52 by Hibernate Tools 4.3.1



/**
 * MovimentId generated by hbm2java
 */
public class MovimentId  implements java.io.Serializable {


     private int idPartida;
     private int numMoviment;

    public MovimentId() {
    }

    public MovimentId(int idPartida, int numMoviment) {
       this.idPartida = idPartida;
       this.numMoviment = numMoviment;
    }
   
    public int getIdPartida() {
        return this.idPartida;
    }
    
    public void setIdPartida(int idPartida) {
        this.idPartida = idPartida;
    }
    public int getNumMoviment() {
        return this.numMoviment;
    }
    
    public void setNumMoviment(int numMoviment) {
        this.numMoviment = numMoviment;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MovimentId) ) return false;
		 MovimentId castOther = ( MovimentId ) other; 
         
		 return (this.getIdPartida()==castOther.getIdPartida())
 && (this.getNumMoviment()==castOther.getNumMoviment());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdPartida();
         result = 37 * result + this.getNumMoviment();
         return result;
   }   


}


