package Damas.entity;
// Generated 04/03/2020 19:27:52 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Partida generated by hbm2java
 */
public class Partida  implements java.io.Serializable {


     private Integer idPartida;
     private Date horaInici;
     private int numMoviments;
     private String guanyador;
     private Set moviments = new HashSet(0);

    public Partida() {
    }

	
    public Partida(Date horaInici, int numMoviments, String guanyador) {
        this.horaInici = horaInici;
        this.numMoviments = numMoviments;
        this.guanyador = guanyador;
    }
    public Partida(Date horaInici, int numMoviments, String guanyador, Set moviments) {
       this.horaInici = horaInici;
       this.numMoviments = numMoviments;
       this.guanyador = guanyador;
       this.moviments = moviments;
    }
   
    public Integer getIdPartida() {
        return this.idPartida;
    }
    
    public void setIdPartida(Integer idPartida) {
        this.idPartida = idPartida;
    }
    public Date getHoraInici() {
        return this.horaInici;
    }
    
    public void setHoraInici(Date horaInici) {
        this.horaInici = horaInici;
    }
    public int getNumMoviments() {
        return this.numMoviments;
    }
    
    public void setNumMoviments(int numMoviments) {
        this.numMoviments = numMoviments;
    }
    public String getGuanyador() {
        return this.guanyador;
    }
    
    public void setGuanyador(String guanyador) {
        this.guanyador = guanyador;
    }
    public Set getMoviments() {
        return this.moviments;
    }
    
    public void setMoviments(Set moviments) {
        this.moviments = moviments;
    }




}


